### ISSUE TITLE
Unable to Pickup or Digup

### ISSUE THREAD

**Issue by DoyleChris** [nyje/visual-bots#1]
Once you place the bot and you want to move it, you are unable to dig it up or pick it up.

**Comment by nyje** [comment]
Two things may stop you from digging out the bot.
1. you cannot (well, it's very hard) dig out the bot with an empty hand, as it says in the instructions, you must have something in hand, 
2. If the bot has dug, it keeps what it digs in it's inventory. Like a chest, and as it says in the instructions, it can only be dug out when empty.

> Dig the bot by hitting it with anything except an empty hand, but bear in mind the bot can only be dug out if it's inventory is empty.

Were either of these the case?

**Comment by DoyleChris** [comment]
I didn't clear the inventory.
